services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    depends_on:
      db:
        condition: service_healthy
      go-judge:
        condition: service_started # Mudamos a dependência

    develop:
      watch:
        - action: sync
          path: ./api/src
          target: /app/src
        - action: rebuild
          path: ./api/package.json
    volumes:
      - ./api:/app
      - /app/node_modules

    command: sh -c "npm install && npm run start:dev"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: autocore_user
      POSTGRES_PASSWORD: autocore_password
      POSTGRES_DB: autocore_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U autocore_user -d autocore_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  web:
    build: ./web
    ports:
      - "8080:80"
    env_file:
      - ./web/.env
    depends_on:
      - api
    develop:
      watch:
        - action: sync
          path: ./web/src
          target: /app/src

  # --- NOVO SERVIÇO: Go-Judge ---
  # Substitui toda a stack complexa do Judge0 (Server, Worker, Redis, DB)
  go-judge:
    image: criyle/go-judge:v1.8.5
    ports:
      - "5050:5050"
    command: -enable-debug
    # --- Configurações Críticas para WSL2 ---
    privileged: true
    shm_size: "256m"
    restart: always

    # 1. Permite que o container manipule syscalls de isolamento
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined

    # 2. Monta o Cgroup do host com permissão de escrita (RW)
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

    # 3. Configurações opcionais de log e memória
    tmpfs:
      - /opt/sandbox:size=128M

  # --- REMOVIDOS: judge0-server, judge0-worker, judge0-db, judge0-redis ---

volumes:
  postgres_data:
  # judge0-db-data: (Removido)
