version: "3.8"

services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      # Configurações do Banco para a API
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=autocore_user # <--- Alinhado
      - DB_PASSWORD=autocore_password # <--- Alinhado
      - DB_DATABASE=autocore_db
      - JWT_SECRET=secretKey
      # Chave da RapidAPI (Certifique-se de que está no .env ou coloque aqui)
      - RAPIDAPI_KEY=${RAPIDAPI_KEY}
    depends_on:
      - db
    volumes:
      - ./api:/app
      - /app/node_modules

  web:
    build: ./web
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - api

  db:
    image: postgres:13
    environment:
      # Configurações de Criação do Banco
      - POSTGRES_USER=autocore_user # <--- Alinhado
      - POSTGRES_PASSWORD=autocore_password # <--- Alinhado
      - POSTGRES_DB=autocore_db
    ports:
      - "5432:5432"
    volumes:
      - autocore_db_data:/var/lib/postgresql/data

volumes:
  autocore_db_data:
